services:
  frontend:
    build: ./FRONTEND
    ports:
      - "5173:5173"
    env_file:
      - ./FRONTEND/.env
    depends_on:
      - backend
  backend:
    build: ./BACKEND
    ports:
      - "3000:3000"
    env_file:
      - ./BACKEND/.env
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:8
    ports:
      - "6379:6379"
volumes:
  mongo-data: